name: 🚀 Deploy website on Staging/Demo Server
on: [push]
jobs:
  web-deploy:
    if: github.ref == 'refs/heads/master'
    name: 🎉 Deploy on Development Branch
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 🚚 Executing Git Pull on Server.
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          command: |
            cd public_html/naturexbd/
            git pull
            php artisan config:clear
            php artisan view:clear
            php artisan route:clear
            php artisan cache:clear
            php artisan route:cache
            php artisan optimize
            composer dump-autoload

          server: ${{ secrets.server_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}

          server-dir: /
